import { css, media, hover, active } from 'glamor';
import c from './colors';

/*
  SKIN
*/

const foreground = {
  fg_black:        css({ color: c.black }),
  fg_nearBlack:    css({ color: c.nearBlack }),
  fg_darkGray:     css({ color: c.darkGray }),
  fg_midGray:      css({ color: c.midGray }),
  fg_gray:         css({ color: c.gray }),
  fg_silver:       css({ color: c.silver }),
  fg_lightSilver:  css({ color: c.lightSilver }),
  fg_moonGray:     css({ color: c.moonGray }),
  fg_lightGray:    css({ color: c.lightGray }),
  fg_nearWhite:    css({ color: c.nearWhite }),
  fg_white:        css({ color: c.white }),

  fg_black90:      css({ color: c.black90 }),
  fg_black80:      css({ color: c.black80 }),
  fg_black70:      css({ color: c.black70 }),
  fg_black60:      css({ color: c.black60 }),
  fg_black50:      css({ color: c.black50 }),
  fg_black40:      css({ color: c.black40 }),
  fg_black30:      css({ color: c.black30 }),
  fg_black20:      css({ color: c.black20 }),
  fg_black15:      css({ color: c.black15 }),
  fg_black10:      css({ color: c.black10 }),
  fg_black05:      css({ color: c.black05 }),
  fg_black025:     css({ color: c.black025 }),
  fg_black0125:    css({ color: c.black0125 }),

  fg_white90:      css({ color: c.white90 }),
  fg_white80:      css({ color: c.white80 }),
  fg_white70:      css({ color: c.white70 }),
  fg_white60:      css({ color: c.white60 }),
  fg_white50:      css({ color: c.white50 }),
  fg_white40:      css({ color: c.white40 }),
  fg_white30:      css({ color: c.white30 }),
  fg_white20:      css({ color: c.white20 }),
  fg_white10:      css({ color: c.white10 }),
  fg_white05:      css({ color: c.white05 }),
  fg_white025:     css({ color: c.white025 }),
  fg_white0125:    css({ color: c.white0125 }),

  fg_darkRed:      css({ color: c.darkRed }),
  fg_red:          css({ color: c.red }),
  fg_lightRed:     css({ color: c.lightRed }),
  fg_orange:       css({ color: c.orange }),
  fg_gold:         css({ color: c.gold }),
  fg_yellow:       css({ color: c.yellow }),
  fg_lightYellow:  css({ color: c.lightYellow }),
  fg_purple:       css({ color: c.purple }),
  fg_lightPurple:  css({ color: c.lightPurple }),
  fg_darkPink:     css({ color: c.darkPink }),
  fg_hotPink:      css({ color: c.hotPink }),
  fg_pink:         css({ color: c.pink }),
  fg_lightPink:    css({ color: c.lightPink }),
  fg_darkGreen:    css({ color: c.darkGreen }),
  fg_green:        css({ color: c.green }),
  fg_lightGreen:   css({ color: c.lightGreen }),
  fg_navy:         css({ color: c.navy }),
  fg_darkBlue:     css({ color: c.darkBlue }),
  fg_blue:         css({ color: c.blue }),
  fg_lightBlue:    css({ color: c.lightBlue }),
  fg_lightestBlue: css({ color: c.lightestBlue }),
  fg_washedBlue:   css({ color: c.washedBlue }),
  fg_washedGreen:  css({ color: c.washedGreen }),
  fg_washedYellow: css({ color: c.washedYellow }),
  fg_washedRed:    css({ color: c.washedRed }),
};

const foregroundHover = {
  hover_fg_black:        hover({ color: c.black }),
  hover_fg_nearBlack:    hover({ color: c.nearBlack }),
  hover_fg_darkGray:     hover({ color: c.darkGray }),
  hover_fg_midGray:      hover({ color: c.midGray }),
  hover_fg_gray:         hover({ color: c.gray }),
  hover_fg_silver:       hover({ color: c.silver }),
  hover_fg_lightSilver:  hover({ color: c.lightSilver }),
  hover_fg_moonGray:     hover({ color: c.moonGray }),
  hover_fg_lightGray:    hover({ color: c.lightGray }),
  hover_fg_nearWhite:    hover({ color: c.nearWhite }),
  hover_fg_white:        hover({ color: c.white }),

  hover_fg_black90:      hover({ color: c.black90 }),
  hover_fg_black80:      hover({ color: c.black80 }),
  hover_fg_black70:      hover({ color: c.black70 }),
  hover_fg_black60:      hover({ color: c.black60 }),
  hover_fg_black50:      hover({ color: c.black50 }),
  hover_fg_black40:      hover({ color: c.black40 }),
  hover_fg_black30:      hover({ color: c.black30 }),
  hover_fg_black20:      hover({ color: c.black20 }),
  hover_fg_black15:      hover({ color: c.black15 }),
  hover_fg_black10:      hover({ color: c.black10 }),
  hover_fg_black05:      hover({ color: c.black05 }),
  hover_fg_black025:     hover({ color: c.black025 }),
  hover_fg_black0125:    hover({ color: c.black0125 }),

  hover_fg_white90:      hover({ color: c.white90 }),
  hover_fg_white80:      hover({ color: c.white80 }),
  hover_fg_white70:      hover({ color: c.white70 }),
  hover_fg_white60:      hover({ color: c.white60 }),
  hover_fg_white50:      hover({ color: c.white50 }),
  hover_fg_white40:      hover({ color: c.white40 }),
  hover_fg_white30:      hover({ color: c.white30 }),
  hover_fg_white20:      hover({ color: c.white20 }),
  hover_fg_white10:      hover({ color: c.white10 }),
  hover_fg_white05:      hover({ color: c.white05 }),
  hover_fg_white025:     hover({ color: c.white025 }),
  hover_fg_white0125:    hover({ color: c.white0125 }),

  hover_fg_darkRed:      hover({ color: c.darkRed }),
  hover_fg_red:          hover({ color: c.red }),
  hover_fg_lightRed:     hover({ color: c.lightRed }),
  hover_fg_orange:       hover({ color: c.orange }),
  hover_fg_gold:         hover({ color: c.gold }),
  hover_fg_yellow:       hover({ color: c.yellow }),
  hover_fg_lightYellow:  hover({ color: c.lightYellow }),
  hover_fg_purple:       hover({ color: c.purple }),
  hover_fg_lightPurple:  hover({ color: c.lightPurple }),
  hover_fg_darkPink:     hover({ color: c.darkPink }),
  hover_fg_hotPink:      hover({ color: c.hotPink }),
  hover_fg_pink:         hover({ color: c.pink }),
  hover_fg_lightPink:    hover({ color: c.lightPink }),
  hover_fg_darkGreen:    hover({ color: c.darkGreen }),
  hover_fg_green:        hover({ color: c.green }),
  hover_fg_lightGreen:   hover({ color: c.lightGreen }),
  hover_fg_navy:         hover({ color: c.navy }),
  hover_fg_darkBlue:     hover({ color: c.darkBlue }),
  hover_fg_blue:         hover({ color: c.blue }),
  hover_fg_lightBlue:    hover({ color: c.lightBlue }),
  hover_fg_lightestBlue: hover({ color: c.lightestBlue }),
  hover_fg_washedBlue:   hover({ color: c.washedBlue }),
  hover_fg_washedGreen:  hover({ color: c.washedGreen }),
  hover_fg_washedYellow: hover({ color: c.washedYellow }),
  hover_fg_washedRed:    hover({ color: c.washedRed }),
};

const background = {
  bg_black:        css({ backgroundColor: c.black }),
  bg_nearBlack:    css({ backgroundColor: c.nearBlack }),
  bg_darkGray:     css({ backgroundColor: c.darkGray }),
  bg_midGray:      css({ backgroundColor: c.midGray }),
  bg_gray:         css({ backgroundColor: c.gray }),
  bg_silver:       css({ backgroundColor: c.silver }),
  bg_lightSilver:  css({ backgroundColor: c.lightSilver }),
  bg_moonGray:     css({ backgroundColor: c.moonGray }),
  bg_lightGray:    css({ backgroundColor: c.lightGray }),
  bg_nearWhite:    css({ backgroundColor: c.nearWhite }),
  bg_white:        css({ backgroundColor: c.white }),

  bg_black90:      css({ backgroundColor: c.black90 }),
  bg_black80:      css({ backgroundColor: c.black80 }),
  bg_black70:      css({ backgroundColor: c.black70 }),
  bg_black60:      css({ backgroundColor: c.black60 }),
  bg_black50:      css({ backgroundColor: c.black50 }),
  bg_black40:      css({ backgroundColor: c.black40 }),
  bg_black30:      css({ backgroundColor: c.black30 }),
  bg_black20:      css({ backgroundColor: c.black20 }),
  bg_black15:      css({ backgroundColor: c.black15 }),
  bg_black10:      css({ backgroundColor: c.black10 }),
  bg_black05:      css({ backgroundColor: c.black05 }),
  bg_black025:     css({ backgroundColor: c.black025 }),
  bg_black0125:    css({ backgroundColor: c.black0125 }),

  bg_white90:      css({ backgroundColor: c.white90 }),
  bg_white80:      css({ backgroundColor: c.white80 }),
  bg_white70:      css({ backgroundColor: c.white70 }),
  bg_white60:      css({ backgroundColor: c.white60 }),
  bg_white50:      css({ backgroundColor: c.white50 }),
  bg_white40:      css({ backgroundColor: c.white40 }),
  bg_white30:      css({ backgroundColor: c.white30 }),
  bg_white20:      css({ backgroundColor: c.white20 }),
  bg_white10:      css({ backgroundColor: c.white10 }),
  bg_white05:      css({ backgroundColor: c.white05 }),
  bg_white025:     css({ backgroundColor: c.white025 }),
  bg_white0125:    css({ backgroundColor: c.white0125 }),

  bg_darkRed:      css({ backgroundColor: c.darkRed }),
  bg_red:          css({ backgroundColor: c.red }),
  bg_lightRed:     css({ backgroundColor: c.lightRed }),
  bg_orange:       css({ backgroundColor: c.orange }),
  bg_gold:         css({ backgroundColor: c.gold }),
  bg_yellow:       css({ backgroundColor: c.yellow }),
  bg_lightYellow:  css({ backgroundColor: c.lightYellow }),
  bg_purple:       css({ backgroundColor: c.purple }),
  bg_lightPurple:  css({ backgroundColor: c.lightPurple }),
  bg_darkPink:     css({ backgroundColor: c.darkPink }),
  bg_hotPink:      css({ backgroundColor: c.hotPink }),
  bg_pink:         css({ backgroundColor: c.pink }),
  bg_lightPink:    css({ backgroundColor: c.lightPink }),
  bg_darkGreen:    css({ backgroundColor: c.darkGreen }),
  bg_green:        css({ backgroundColor: c.green }),
  bg_lightGreen:   css({ backgroundColor: c.lightGreen }),
  bg_navy:         css({ backgroundColor: c.navy }),
  bg_darkBlue:     css({ backgroundColor: c.darkBlue }),
  bg_blue:         css({ backgroundColor: c.blue }),
  bg_lightBlue:    css({ backgroundColor: c.lightBlue }),
  bg_lightestBlue: css({ backgroundColor: c.lightestBlue }),
  bg_washedBlue:   css({ backgroundColor: c.washedBlue }),
  bg_washedGreen:  css({ backgroundColor: c.washedGreen }),
  bg_washedYellow: css({ backgroundColor: c.washedYellow }),
  bg_washedRed:    css({ backgroundColor: c.washedRed }),
};

const backgroundHover = {
  hover_bg_black:        hover({ backgroundColor: c.black }),
  hover_bg_nearBlack:    hover({ backgroundColor: c.nearBlack }),
  hover_bg_darkGray:     hover({ backgroundColor: c.darkGray }),
  hover_bg_midGray:      hover({ backgroundColor: c.midGray }),
  hover_bg_gray:         hover({ backgroundColor: c.gray }),
  hover_bg_silver:       hover({ backgroundColor: c.silver }),
  hover_bg_lightSilver:  hover({ backgroundColor: c.lightSilver }),
  hover_bg_moonGray:     hover({ backgroundColor: c.moonGray }),
  hover_bg_lightGray:    hover({ backgroundColor: c.lightGray }),
  hover_bg_nearWhite:    hover({ backgroundColor: c.nearWhite }),
  hover_bg_white:        hover({ backgroundColor: c.white }),

  hover_bg_black90:      hover({ backgroundColor: c.black90 }),
  hover_bg_black80:      hover({ backgroundColor: c.black80 }),
  hover_bg_black70:      hover({ backgroundColor: c.black70 }),
  hover_bg_black60:      hover({ backgroundColor: c.black60 }),
  hover_bg_black50:      hover({ backgroundColor: c.black50 }),
  hover_bg_black40:      hover({ backgroundColor: c.black40 }),
  hover_bg_black30:      hover({ backgroundColor: c.black30 }),
  hover_bg_black20:      hover({ backgroundColor: c.black20 }),
  hover_bg_black15:      hover({ backgroundColor: c.black15 }),
  hover_bg_black10:      hover({ backgroundColor: c.black10 }),
  hover_bg_black05:      hover({ backgroundColor: c.black05 }),
  hover_bg_black025:     hover({ backgroundColor: c.black025 }),
  hover_bg_black0125:    hover({ backgroundColor: c.black0125 }),

  hover_bg_white90:      hover({ backgroundColor: c.white90 }),
  hover_bg_white80:      hover({ backgroundColor: c.white80 }),
  hover_bg_white70:      hover({ backgroundColor: c.white70 }),
  hover_bg_white60:      hover({ backgroundColor: c.white60 }),
  hover_bg_white50:      hover({ backgroundColor: c.white50 }),
  hover_bg_white40:      hover({ backgroundColor: c.white40 }),
  hover_bg_white30:      hover({ backgroundColor: c.white30 }),
  hover_bg_white20:      hover({ backgroundColor: c.white20 }),
  hover_bg_white10:      hover({ backgroundColor: c.white10 }),
  hover_bg_white05:      hover({ backgroundColor: c.white05 }),
  hover_bg_white025:     hover({ backgroundColor: c.white025 }),
  hover_bg_white0125:    hover({ backgroundColor: c.white0125 }),

  hover_bg_darkRed:      hover({ backgroundColor: c.darkRed }),
  hover_bg_red:          hover({ backgroundColor: c.red }),
  hover_bg_lightRed:     hover({ backgroundColor: c.lightRed }),
  hover_bg_orange:       hover({ backgroundColor: c.orange }),
  hover_bg_gold:         hover({ backgroundColor: c.gold }),
  hover_bg_yellow:       hover({ backgroundColor: c.yellow }),
  hover_bg_lightYellow:  hover({ backgroundColor: c.lightYellow }),
  hover_bg_purple:       hover({ backgroundColor: c.purple }),
  hover_bg_lightPurple:  hover({ backgroundColor: c.lightPurple }),
  hover_bg_darkPink:     hover({ backgroundColor: c.darkPink }),
  hover_bg_hotPink:      hover({ backgroundColor: c.hotPink }),
  hover_bg_pink:         hover({ backgroundColor: c.pink }),
  hover_bg_lightPink:    hover({ backgroundColor: c.lightPink }),
  hover_bg_darkGreen:    hover({ backgroundColor: c.darkGreen }),
  hover_bg_green:        hover({ backgroundColor: c.green }),
  hover_bg_lightGreen:   hover({ backgroundColor: c.lightGreen }),
  hover_bg_navy:         hover({ backgroundColor: c.navy }),
  hover_bg_darkBlue:     hover({ backgroundColor: c.darkBlue }),
  hover_bg_blue:         hover({ backgroundColor: c.blue }),
  hover_bg_lightBlue:    hover({ backgroundColor: c.lightBlue }),
  hover_bg_lightestBlue: hover({ backgroundColor: c.lightestBlue }),
  hover_bg_washedBlue:   hover({ backgroundColor: c.washedBlue }),
  hover_bg_washedGreen:  hover({ backgroundColor: c.washedGreen }),
  hover_bg_washedYellow: hover({ backgroundColor: c.washedYellow }),
  hover_bg_washedRed:    hover({ backgroundColor: c.washedRed }),
};

const shadow = {
  bs: css({ boxShadow: '4px 4px 0 rgba(0,0,0, 0.1)' }),
  bs_straight: css({ boxShadow: '0 4px 0 rgba(0,0,0, 0.1)' }),
  bs_soft: css({ boxShadow: '0 2px 20px rgba(0,0,0, 0.25)' }),
};

const dims = {
  o80: css({  opacity: 0.80 }),
  o70: css({  opacity: 0.70 }),
  o50: css({  opacity: 0.50 }),
  o01: css({  opacity: 0.01 }),
  o0: css({   opacity: 0 }),
};

export const rules = {
  ...foreground,
  ...foregroundHover,
  ...background,
  ...backgroundHover,
  ...shadow,
  ...dims,
};

export default rules;
